apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend
generatorOptions:
  annotations:
    generated: "false"
  disableNameSuffixHash: true

configMapGenerator:
  - envs:
      - .dev.env
    name: feedback-backend-env-file

# secretGenerator:
#   - files:
#       - secrets/.dockerconfigjson
#     name: feedback-backend-registry-credentials
#     type: kubernetes.io/dockerconfigjson

resources:
  - service.yaml
  - deployment.yaml
  - hpa.yaml

patches:
  - path: service-nodeport.yaml
