apiVersion: v1
kind: Service
metadata:
  name: feedback-backend-service
  namespace: uat-backend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: feedback-backend.uat-k8.livingthings.co.in
spec:
  type: NodePort
